package com.sandwich.model;


import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;
import java.util.UUID;

@Entity
public class Sandwich implements Serializable {

    // database primary key
    // since this field is autogenerated by the database there is not setId()
    // method, only a getId() method
    @Id
    @NotNull
    @NotBlank
    @Column(nullable = false, unique = true)
    private UUID sandwichId = UUID.randomUUID();

    @NotNull
    @NotBlank
    @Column(nullable = false, unique = true)
    private String publicKey;

    @Column(nullable = false, unique = true)
    @NotNull
    @NotBlank
    @Size(min = 1, max = 50)
    private String designation;

    @Column(nullable = false)
    @NotNull
    @NotBlank
    @Size(min = 1, max = 1024)
    private String description;

    @Column(nullable = false)
    @ElementCollection
    private List<Ingredient> listOfIngredients;

    public Sandwich(final UUID sandwichId,final String publicKey, final String designation, final String description, final List<Ingredient> listOfIngredients) {
        this.sandwichId=sandwichId;
        setPublicKey(publicKey);
        setDesignation(designation);
        setDescription(description);
        setListOfIngredients(listOfIngredients);
    }

    public Sandwich(String publicKey, String designation, String description, List<Ingredient> listOfIngredients) {
        setPublicKey(publicKey);
        setDesignation(designation);
        setDescription(description);
        setListOfIngredients(listOfIngredients);
    }

    public Sandwich() {
    }

    //Getter and setter


    public UUID getSandwichId() {
        return sandwichId;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        if (publicKey == null || publicKey.isEmpty()) {
            throw new IllegalArgumentException("'publicKey' is a mandatory attribute of Ingredient");
        }
        if (publicKey.length()<3){
            throw new IllegalArgumentException("'publicKey' has a minimum of 3 characters");
        }
        if (publicKey.length()>5){
            throw new IllegalArgumentException("'publicKey' has a maximum of 5 characters");
        }
        if (publicKey.trim().length() == 0){
            throw new IllegalArgumentException("'publicKey' cannot have white spaces");
        }
        if (!publicKey.matches("[a-zA-Z0-9]+")){
            throw new IllegalArgumentException("'publicKey' has invalid characters");
        }
        this.publicKey = publicKey.trim();
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        if (designation == null || designation.isEmpty()) {
            throw new IllegalArgumentException("'Designation' is a mandatory attribute of Sandwich");
        }
        if (designation.length()>50){
            throw new IllegalArgumentException("'Designation' has a maximum of 50 characters");
        }
        if (designation.trim().length() == 0){
            throw new IllegalArgumentException("'Designation' cannot have only white spaces");
        }

        this.designation = designation;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        if (description == null || description.isEmpty()) {
            throw new IllegalArgumentException("'Description' is a mandatory attribute of Sandwich");
        }

        if (description.length()>1024){
            throw new IllegalArgumentException("'Description' has a maximum of 1024 characters");
        }
        if (description.trim().length() == 0){
            throw new IllegalArgumentException("'Description' cannot have only white spaces");
        }

        this.description = description;
    }

    public List<Ingredient> getListOfIngredients() {
        return listOfIngredients;
    }

    public void setListOfIngredients(List<Ingredient> listOfIngredients) {
        if(listOfIngredients.size()<2){
            throw new IllegalArgumentException("'listOfIngredients' is a mandatory attribute of Sandwich and you must choose at least two. For example: Bread and cheese");
        }
        this.listOfIngredients = listOfIngredients;
    }
}
