package com.votes.model;
import java.io.Serializable;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@Entity
public class Product implements Serializable {

    // database primary key
    // since this field is autogenerated by the database there is not setId()
    // method, only a getId() method
    @Id
    @Column(nullable = false, unique = true)
    @NotNull
    @NotBlank
    @Size(min = 12, max = 12)
    private String sku;

    // business identity
    @Column(nullable = false)
    @NotNull
    @NotBlank
    @Size(min = 1, max = 50)
    private String designation;

    @Column(nullable = true)
    @NotNull
    @NotBlank
    @Size(min = 1, max = 1024)
    private String description;


    @Column(nullable = true)
    private String image;


    protected Product() {
        // got ORM only
    }

    public Product(final String designation) {
        setDesignation(designation);
    }

    // for reconstructing the object from service layer back to persistence layer
    private Product(final String sku, final String designation  ) {
        //this.sku = Objects.requireNonNull(sku);
        setSku(sku);
        setDesignation(designation);
    }

    // for reconstructing the object from service layer back to persistence layer
    public Product(final String sku, final String designation, final String description, final String image) {
        this(sku, designation);

        setDescription(description);
        setImage(image);
    }


    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        if (sku.length()!=12 || !sku.matches("[a-zA-Z0-9]+")) {
            throw new IllegalArgumentException("'SKU' has not a correct format");
        }
        this.sku = sku;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        if (designation == null || designation.isEmpty()) {
            throw new IllegalArgumentException("'Designation' is a mandatory attribute of Product");
        }
        if (designation.length()>50){
            throw new IllegalArgumentException("'Designation' has a maximum of 50 characters");
        }
        if (designation.trim().length() == 0){
            throw new IllegalArgumentException("'Designation' cannot have only white spaces");
        }

        this.designation = designation;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        if (description == null || description.isEmpty()) {
            throw new IllegalArgumentException("'Description' is a mandatory attribute of Product");
        }

        if (description.length()>1024){
            throw new IllegalArgumentException("'Description' has a maximum of 1024 characters");
        }
        if (description.trim().length() == 0){
            throw new IllegalArgumentException("'Description' cannot have only white spaces");
        }

        this.description = description;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
}
